import { type CountrySummary, countrySummarySchema } from "@/lib/types/score";

export const allCountries = [
  {
    code: "AF",
    name: "Afghanistan",
    region: "Asia / Southern Asia",
    latitude: 33,
    longitude: 65,
    focalCity: "Kabul",
  },
  {
    code: "AX",
    name: "Åland Islands",
    region: "Europe / Northern Europe",
    latitude: 60.116_667,
    longitude: 19.9,
    focalCity: "Mariehamn",
  },
  {
    code: "AL",
    name: "Albania",
    region: "Europe / Southeast Europe",
    latitude: 41,
    longitude: 20,
    focalCity: "Tirana",
  },
  {
    code: "DZ",
    name: "Algeria",
    region: "Africa / Northern Africa",
    latitude: 28,
    longitude: 3,
    focalCity: "Algiers",
  },
  {
    code: "AS",
    name: "American Samoa",
    region: "Oceania / Polynesia",
    latitude: -14.333_333_33,
    longitude: -170,
    focalCity: "Pago Pago",
  },
  {
    code: "AD",
    name: "Andorra",
    region: "Europe / Southern Europe",
    latitude: 42.5,
    longitude: 1.5,
    focalCity: "Andorra la Vella",
  },
  {
    code: "AO",
    name: "Angola",
    region: "Africa / Middle Africa",
    latitude: -12.5,
    longitude: 18.5,
    focalCity: "Luanda",
  },
  {
    code: "AI",
    name: "Anguilla",
    region: "Americas / Caribbean",
    latitude: 18.25,
    longitude: -63.166_666_66,
    focalCity: "The Valley",
  },
  {
    code: "AQ",
    name: "Antarctica",
    region: "Antarctic",
    latitude: -90,
    longitude: 0,
    focalCity: "Antarctica",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    region: "Americas / Caribbean",
    latitude: 17.05,
    longitude: -61.8,
    focalCity: "Saint John\u0027s",
  },
  {
    code: "AR",
    name: "Argentina",
    region: "Americas / South America",
    latitude: -34,
    longitude: -64,
    focalCity: "Buenos Aires",
  },
  {
    code: "AM",
    name: "Armenia",
    region: "Asia / Western Asia",
    latitude: 40,
    longitude: 45,
    focalCity: "Yerevan",
  },
  {
    code: "AW",
    name: "Aruba",
    region: "Americas / Caribbean",
    latitude: 12.5,
    longitude: -69.966_666_66,
    focalCity: "Oranjestad",
  },
  {
    code: "AU",
    name: "Australia",
    region: "Oceania / Australia and New Zealand",
    latitude: -27,
    longitude: 133,
    focalCity: "Canberra",
  },
  {
    code: "AT",
    name: "Austria",
    region: "Europe / Central Europe",
    latitude: 47.333_333_33,
    longitude: 13.333_333_33,
    focalCity: "Vienna",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    region: "Asia / Western Asia",
    latitude: 40.5,
    longitude: 47.5,
    focalCity: "Baku",
  },
  {
    code: "BS",
    name: "Bahamas",
    region: "Americas / Caribbean",
    latitude: 24.25,
    longitude: -76,
    focalCity: "Nassau",
  },
  {
    code: "BH",
    name: "Bahrain",
    region: "Asia / Western Asia",
    latitude: 26,
    longitude: 50.55,
    focalCity: "Manama",
  },
  {
    code: "BD",
    name: "Bangladesh",
    region: "Asia / Southern Asia",
    latitude: 24,
    longitude: 90,
    focalCity: "Dhaka",
  },
  {
    code: "BB",
    name: "Barbados",
    region: "Americas / Caribbean",
    latitude: 13.166_666_66,
    longitude: -59.533_333_33,
    focalCity: "Bridgetown",
  },
  {
    code: "BY",
    name: "Belarus",
    region: "Europe / Eastern Europe",
    latitude: 53,
    longitude: 28,
    focalCity: "Minsk",
  },
  {
    code: "BE",
    name: "Belgium",
    region: "Europe / Western Europe",
    latitude: 50.833_333_33,
    longitude: 4,
    focalCity: "Brussels",
  },
  {
    code: "BZ",
    name: "Belize",
    region: "Americas / Central America",
    latitude: 17.25,
    longitude: -88.75,
    focalCity: "Belmopan",
  },
  {
    code: "BJ",
    name: "Benin",
    region: "Africa / Western Africa",
    latitude: 9.5,
    longitude: 2.25,
    focalCity: "Porto-Novo",
  },
  {
    code: "BM",
    name: "Bermuda",
    region: "Americas / North America",
    latitude: 32.333_333_33,
    longitude: -64.75,
    focalCity: "Hamilton",
  },
  {
    code: "BT",
    name: "Bhutan",
    region: "Asia / Southern Asia",
    latitude: 27.5,
    longitude: 90.5,
    focalCity: "Thimphu",
  },
  {
    code: "BO",
    name: "Bolivia",
    region: "Americas / South America",
    latitude: -17,
    longitude: -65,
    focalCity: "Sucre",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    region: "Europe / Southeast Europe",
    latitude: 44,
    longitude: 18,
    focalCity: "Sarajevo",
  },
  {
    code: "BW",
    name: "Botswana",
    region: "Africa / Southern Africa",
    latitude: -22,
    longitude: 24,
    focalCity: "Gaborone",
  },
  {
    code: "BV",
    name: "Bouvet Island",
    region: "Antarctic",
    latitude: -54.433_333_33,
    longitude: 3.4,
    focalCity: "Bouvet Island",
  },
  {
    code: "BR",
    name: "Brazil",
    region: "Americas / South America",
    latitude: -10,
    longitude: -55,
    focalCity: "Brasília",
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    region: "Africa / Eastern Africa",
    latitude: -6,
    longitude: 71.5,
    focalCity: "Diego Garcia",
  },
  {
    code: "VG",
    name: "British Virgin Islands",
    region: "Americas / Caribbean",
    latitude: 18.431_383,
    longitude: -64.623_05,
    focalCity: "Road Town",
  },
  {
    code: "BN",
    name: "Brunei",
    region: "Asia / South-Eastern Asia",
    latitude: 4.5,
    longitude: 114.666_666_66,
    focalCity: "Bandar Seri Begawan",
  },
  {
    code: "BG",
    name: "Bulgaria",
    region: "Europe / Southeast Europe",
    latitude: 43,
    longitude: 25,
    focalCity: "Sofia",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    region: "Africa / Western Africa",
    latitude: 13,
    longitude: -2,
    focalCity: "Ouagadougou",
  },
  {
    code: "BI",
    name: "Burundi",
    region: "Africa / Eastern Africa",
    latitude: -3.5,
    longitude: 30,
    focalCity: "Gitega",
  },
  {
    code: "KH",
    name: "Cambodia",
    region: "Asia / South-Eastern Asia",
    latitude: 13,
    longitude: 105,
    focalCity: "Phnom Penh",
  },
  {
    code: "CM",
    name: "Cameroon",
    region: "Africa / Middle Africa",
    latitude: 6,
    longitude: 12,
    focalCity: "Yaoundé",
  },
  {
    code: "CA",
    name: "Canada",
    region: "Americas / North America",
    latitude: 60,
    longitude: -95,
    focalCity: "Ottawa",
  },
  {
    code: "CV",
    name: "Cape Verde",
    region: "Africa / Western Africa",
    latitude: 16,
    longitude: -24,
    focalCity: "Praia",
  },
  {
    code: "BQ",
    name: "Caribbean Netherlands",
    region: "Americas / Caribbean",
    latitude: 12.18,
    longitude: -68.25,
    focalCity: "Kralendijk",
  },
  {
    code: "KY",
    name: "Cayman Islands",
    region: "Americas / Caribbean",
    latitude: 19.5,
    longitude: -80.5,
    focalCity: "George Town",
  },
  {
    code: "CF",
    name: "Central African Republic",
    region: "Africa / Middle Africa",
    latitude: 7,
    longitude: 21,
    focalCity: "Bangui",
  },
  {
    code: "TD",
    name: "Chad",
    region: "Africa / Middle Africa",
    latitude: 15,
    longitude: 19,
    focalCity: "N\u0027Djamena",
  },
  {
    code: "CL",
    name: "Chile",
    region: "Americas / South America",
    latitude: -30,
    longitude: -71,
    focalCity: "Santiago",
  },
  {
    code: "CN",
    name: "China",
    region: "Asia / Eastern Asia",
    latitude: 35,
    longitude: 105,
    focalCity: "Beijing",
  },
  {
    code: "CX",
    name: "Christmas Island",
    region: "Oceania / Australia and New Zealand",
    latitude: -10.5,
    longitude: 105.666_666_66,
    focalCity: "Flying Fish Cove",
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    region: "Oceania / Australia and New Zealand",
    latitude: -12.5,
    longitude: 96.833_333_33,
    focalCity: "West Island",
  },
  {
    code: "CO",
    name: "Colombia",
    region: "Americas / South America",
    latitude: 4,
    longitude: -72,
    focalCity: "Bogotá",
  },
  {
    code: "KM",
    name: "Comoros",
    region: "Africa / Eastern Africa",
    latitude: -12.166_666_66,
    longitude: 44.25,
    focalCity: "Moroni",
  },
  {
    code: "CG",
    name: "Congo",
    region: "Africa / Middle Africa",
    latitude: -1,
    longitude: 15,
    focalCity: "Brazzaville",
  },
  {
    code: "CK",
    name: "Cook Islands",
    region: "Oceania / Polynesia",
    latitude: -21.233_333_33,
    longitude: -159.766_666_66,
    focalCity: "Avarua",
  },
  {
    code: "CR",
    name: "Costa Rica",
    region: "Americas / Central America",
    latitude: 10,
    longitude: -84,
    focalCity: "San José",
  },
  {
    code: "HR",
    name: "Croatia",
    region: "Europe / Southeast Europe",
    latitude: 45.166_666_66,
    longitude: 15.5,
    focalCity: "Zagreb",
  },
  {
    code: "CU",
    name: "Cuba",
    region: "Americas / Caribbean",
    latitude: 21.5,
    longitude: -80,
    focalCity: "Havana",
  },
  {
    code: "CW",
    name: "Curaçao",
    region: "Americas / Caribbean",
    latitude: 12.116_667,
    longitude: -68.933_333,
    focalCity: "Willemstad",
  },
  {
    code: "CY",
    name: "Cyprus",
    region: "Europe / Southern Europe",
    latitude: 35,
    longitude: 33,
    focalCity: "Nicosia",
  },
  {
    code: "CZ",
    name: "Czechia",
    region: "Europe / Central Europe",
    latitude: 49.75,
    longitude: 15.5,
    focalCity: "Prague",
  },
  {
    code: "DK",
    name: "Denmark",
    region: "Europe / Northern Europe",
    latitude: 56,
    longitude: 10,
    focalCity: "Copenhagen",
  },
  {
    code: "DJ",
    name: "Djibouti",
    region: "Africa / Eastern Africa",
    latitude: 11.5,
    longitude: 43,
    focalCity: "Djibouti",
  },
  {
    code: "DM",
    name: "Dominica",
    region: "Americas / Caribbean",
    latitude: 15.416_666_66,
    longitude: -61.333_333_33,
    focalCity: "Roseau",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    region: "Americas / Caribbean",
    latitude: 19,
    longitude: -70.666_666_66,
    focalCity: "Santo Domingo",
  },
  {
    code: "CD",
    name: "DR Congo",
    region: "Africa / Middle Africa",
    latitude: 0,
    longitude: 25,
    focalCity: "Kinshasa",
  },
  {
    code: "EC",
    name: "Ecuador",
    region: "Americas / South America",
    latitude: -2,
    longitude: -77.5,
    focalCity: "Quito",
  },
  {
    code: "EG",
    name: "Egypt",
    region: "Africa / Northern Africa",
    latitude: 27,
    longitude: 30,
    focalCity: "Cairo",
  },
  {
    code: "SV",
    name: "El Salvador",
    region: "Americas / Central America",
    latitude: 13.833_333_33,
    longitude: -88.916_666_66,
    focalCity: "San Salvador",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    region: "Africa / Middle Africa",
    latitude: 2,
    longitude: 10,
    focalCity: "Malabo",
  },
  {
    code: "ER",
    name: "Eritrea",
    region: "Africa / Eastern Africa",
    latitude: 15,
    longitude: 39,
    focalCity: "Asmara",
  },
  {
    code: "EE",
    name: "Estonia",
    region: "Europe / Northern Europe",
    latitude: 59,
    longitude: 26,
    focalCity: "Tallinn",
  },
  {
    code: "SZ",
    name: "Eswatini",
    region: "Africa / Southern Africa",
    latitude: -26.5,
    longitude: 31.5,
    focalCity: "Lobamba",
  },
  {
    code: "ET",
    name: "Ethiopia",
    region: "Africa / Eastern Africa",
    latitude: 8,
    longitude: 38,
    focalCity: "Addis Ababa",
  },
  {
    code: "FK",
    name: "Falkland Islands",
    region: "Americas / South America",
    latitude: -51.75,
    longitude: -59,
    focalCity: "Stanley",
  },
  {
    code: "FO",
    name: "Faroe Islands",
    region: "Europe / Northern Europe",
    latitude: 62,
    longitude: -7,
    focalCity: "Tórshavn",
  },
  {
    code: "FJ",
    name: "Fiji",
    region: "Oceania / Melanesia",
    latitude: -18,
    longitude: 175,
    focalCity: "Suva",
  },
  {
    code: "FI",
    name: "Finland",
    region: "Europe / Northern Europe",
    latitude: 64,
    longitude: 26,
    focalCity: "Helsinki",
  },
  {
    code: "FR",
    name: "France",
    region: "Europe / Western Europe",
    latitude: 46,
    longitude: 2,
    focalCity: "Paris",
  },
  {
    code: "GF",
    name: "French Guiana",
    region: "Americas / South America",
    latitude: 4,
    longitude: -53,
    focalCity: "Cayenne",
  },
  {
    code: "PF",
    name: "French Polynesia",
    region: "Oceania / Polynesia",
    latitude: -15,
    longitude: -140,
    focalCity: "Papeetē",
  },
  {
    code: "TF",
    name: "French Southern and Antarctic Lands",
    region: "Antarctic",
    latitude: -49.25,
    longitude: 69.167,
    focalCity: "Port-aux-Français",
  },
  {
    code: "GA",
    name: "Gabon",
    region: "Africa / Middle Africa",
    latitude: -1,
    longitude: 11.75,
    focalCity: "Libreville",
  },
  {
    code: "GM",
    name: "Gambia",
    region: "Africa / Western Africa",
    latitude: 13.466_666_66,
    longitude: -16.566_666_66,
    focalCity: "Banjul",
  },
  {
    code: "GE",
    name: "Georgia",
    region: "Asia / Western Asia",
    latitude: 42,
    longitude: 43.5,
    focalCity: "Tbilisi",
  },
  {
    code: "DE",
    name: "Germany",
    region: "Europe / Western Europe",
    latitude: 51,
    longitude: 9,
    focalCity: "Berlin",
  },
  {
    code: "GH",
    name: "Ghana",
    region: "Africa / Western Africa",
    latitude: 8,
    longitude: -2,
    focalCity: "Accra",
  },
  {
    code: "GI",
    name: "Gibraltar",
    region: "Europe / Southern Europe",
    latitude: 36.133_333_33,
    longitude: -5.35,
    focalCity: "Gibraltar",
  },
  {
    code: "GR",
    name: "Greece",
    region: "Europe / Southern Europe",
    latitude: 39,
    longitude: 22,
    focalCity: "Athens",
  },
  {
    code: "GL",
    name: "Greenland",
    region: "Americas / North America",
    latitude: 72,
    longitude: -40,
    focalCity: "Nuuk",
  },
  {
    code: "GD",
    name: "Grenada",
    region: "Americas / Caribbean",
    latitude: 12.116_666_66,
    longitude: -61.666_666_66,
    focalCity: "St. George\u0027s",
  },
  {
    code: "GP",
    name: "Guadeloupe",
    region: "Americas / Caribbean",
    latitude: 16.25,
    longitude: -61.583_333,
    focalCity: "Basse-Terre",
  },
  {
    code: "GU",
    name: "Guam",
    region: "Oceania / Micronesia",
    latitude: 13.466_666_66,
    longitude: 144.783_333_33,
    focalCity: "Hagåtña",
  },
  {
    code: "GT",
    name: "Guatemala",
    region: "Americas / Central America",
    latitude: 15.5,
    longitude: -90.25,
    focalCity: "Guatemala City",
  },
  {
    code: "GG",
    name: "Guernsey",
    region: "Europe / Northern Europe",
    latitude: 49.466_666_66,
    longitude: -2.583_333_33,
    focalCity: "St. Peter Port",
  },
  {
    code: "GN",
    name: "Guinea",
    region: "Africa / Western Africa",
    latitude: 11,
    longitude: -10,
    focalCity: "Conakry",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    region: "Africa / Western Africa",
    latitude: 12,
    longitude: -15,
    focalCity: "Bissau",
  },
  {
    code: "GY",
    name: "Guyana",
    region: "Americas / South America",
    latitude: 5,
    longitude: -59,
    focalCity: "Georgetown",
  },
  {
    code: "HT",
    name: "Haiti",
    region: "Americas / Caribbean",
    latitude: 19,
    longitude: -72.416_666_66,
    focalCity: "Port-au-Prince",
  },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    region: "Antarctic",
    latitude: -53.1,
    longitude: 72.516_666_66,
    focalCity: "Heard Island and McDonald Islands",
  },
  {
    code: "HN",
    name: "Honduras",
    region: "Americas / Central America",
    latitude: 15,
    longitude: -86.5,
    focalCity: "Tegucigalpa",
  },
  {
    code: "HK",
    name: "Hong Kong",
    region: "Asia / Eastern Asia",
    latitude: 22.267,
    longitude: 114.188,
    focalCity: "City of Victoria",
  },
  {
    code: "HU",
    name: "Hungary",
    region: "Europe / Central Europe",
    latitude: 47,
    longitude: 20,
    focalCity: "Budapest",
  },
  {
    code: "IS",
    name: "Iceland",
    region: "Europe / Northern Europe",
    latitude: 65,
    longitude: -18,
    focalCity: "Reykjavik",
  },
  {
    code: "IN",
    name: "India",
    region: "Asia / Southern Asia",
    latitude: 20,
    longitude: 77,
    focalCity: "New Delhi",
  },
  {
    code: "ID",
    name: "Indonesia",
    region: "Asia / South-Eastern Asia",
    latitude: -5,
    longitude: 120,
    focalCity: "Jakarta",
  },
  {
    code: "IR",
    name: "Iran",
    region: "Asia / Southern Asia",
    latitude: 32,
    longitude: 53,
    focalCity: "Tehran",
  },
  {
    code: "IQ",
    name: "Iraq",
    region: "Asia / Western Asia",
    latitude: 33,
    longitude: 44,
    focalCity: "Baghdad",
  },
  {
    code: "IE",
    name: "Ireland",
    region: "Europe / Northern Europe",
    latitude: 53,
    longitude: -8,
    focalCity: "Dublin",
  },
  {
    code: "IM",
    name: "Isle of Man",
    region: "Europe / Northern Europe",
    latitude: 54.25,
    longitude: -4.5,
    focalCity: "Douglas",
  },
  {
    code: "IL",
    name: "Israel",
    region: "Asia / Western Asia",
    latitude: 31.47,
    longitude: 35.13,
    focalCity: "Jerusalem",
  },
  {
    code: "IT",
    name: "Italy",
    region: "Europe / Southern Europe",
    latitude: 42.833_333_33,
    longitude: 12.833_333_33,
    focalCity: "Rome",
  },
  {
    code: "CI",
    name: "Ivory Coast",
    region: "Africa / Western Africa",
    latitude: 8,
    longitude: -5,
    focalCity: "Yamoussoukro",
  },
  {
    code: "JM",
    name: "Jamaica",
    region: "Americas / Caribbean",
    latitude: 18.25,
    longitude: -77.5,
    focalCity: "Kingston",
  },
  {
    code: "JP",
    name: "Japan",
    region: "Asia / Eastern Asia",
    latitude: 36,
    longitude: 138,
    focalCity: "Tokyo",
  },
  {
    code: "JE",
    name: "Jersey",
    region: "Europe / Northern Europe",
    latitude: 49.25,
    longitude: -2.166_666_66,
    focalCity: "Saint Helier",
  },
  {
    code: "JO",
    name: "Jordan",
    region: "Asia / Western Asia",
    latitude: 31,
    longitude: 36,
    focalCity: "Amman",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    region: "Asia / Central Asia",
    latitude: 48,
    longitude: 68,
    focalCity: "Astana",
  },
  {
    code: "KE",
    name: "Kenya",
    region: "Africa / Eastern Africa",
    latitude: 1,
    longitude: 38,
    focalCity: "Nairobi",
  },
  {
    code: "KI",
    name: "Kiribati",
    region: "Oceania / Micronesia",
    latitude: 1.416_666_66,
    longitude: 173,
    focalCity: "South Tarawa",
  },
  {
    code: "KW",
    name: "Kuwait",
    region: "Asia / Western Asia",
    latitude: 29.5,
    longitude: 45.75,
    focalCity: "Kuwait City",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    region: "Asia / Central Asia",
    latitude: 41,
    longitude: 75,
    focalCity: "Bishkek",
  },
  {
    code: "LA",
    name: "Laos",
    region: "Asia / South-Eastern Asia",
    latitude: 18,
    longitude: 105,
    focalCity: "Vientiane",
  },
  {
    code: "LV",
    name: "Latvia",
    region: "Europe / Northern Europe",
    latitude: 57,
    longitude: 25,
    focalCity: "Riga",
  },
  {
    code: "LB",
    name: "Lebanon",
    region: "Asia / Western Asia",
    latitude: 33.833_333_33,
    longitude: 35.833_333_33,
    focalCity: "Beirut",
  },
  {
    code: "LS",
    name: "Lesotho",
    region: "Africa / Southern Africa",
    latitude: -29.5,
    longitude: 28.5,
    focalCity: "Maseru",
  },
  {
    code: "LR",
    name: "Liberia",
    region: "Africa / Western Africa",
    latitude: 6.5,
    longitude: -9.5,
    focalCity: "Monrovia",
  },
  {
    code: "LY",
    name: "Libya",
    region: "Africa / Northern Africa",
    latitude: 25,
    longitude: 17,
    focalCity: "Tripoli",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    region: "Europe / Western Europe",
    latitude: 47.266_666_66,
    longitude: 9.533_333_33,
    focalCity: "Vaduz",
  },
  {
    code: "LT",
    name: "Lithuania",
    region: "Europe / Northern Europe",
    latitude: 56,
    longitude: 24,
    focalCity: "Vilnius",
  },
  {
    code: "LU",
    name: "Luxembourg",
    region: "Europe / Western Europe",
    latitude: 49.75,
    longitude: 6.166_666_66,
    focalCity: "Luxembourg",
  },
  {
    code: "MO",
    name: "Macau",
    region: "Asia / Eastern Asia",
    latitude: 22.166_666_66,
    longitude: 113.55,
    focalCity: "Macau",
  },
  {
    code: "MG",
    name: "Madagascar",
    region: "Africa / Eastern Africa",
    latitude: -20,
    longitude: 47,
    focalCity: "Antananarivo",
  },
  {
    code: "MW",
    name: "Malawi",
    region: "Africa / Eastern Africa",
    latitude: -13.5,
    longitude: 34,
    focalCity: "Lilongwe",
  },
  {
    code: "MY",
    name: "Malaysia",
    region: "Asia / South-Eastern Asia",
    latitude: 2.5,
    longitude: 112.5,
    focalCity: "Kuala Lumpur",
  },
  {
    code: "MV",
    name: "Maldives",
    region: "Asia / Southern Asia",
    latitude: 3.25,
    longitude: 73,
    focalCity: "Malé",
  },
  {
    code: "ML",
    name: "Mali",
    region: "Africa / Western Africa",
    latitude: 17,
    longitude: -4,
    focalCity: "Bamako",
  },
  {
    code: "MT",
    name: "Malta",
    region: "Europe / Southern Europe",
    latitude: 35.833_333_33,
    longitude: 14.583_333_33,
    focalCity: "Valletta",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    region: "Oceania / Micronesia",
    latitude: 9,
    longitude: 168,
    focalCity: "Majuro",
  },
  {
    code: "MQ",
    name: "Martinique",
    region: "Americas / Caribbean",
    latitude: 14.666_667,
    longitude: -61,
    focalCity: "Fort-de-France",
  },
  {
    code: "MR",
    name: "Mauritania",
    region: "Africa / Western Africa",
    latitude: 20,
    longitude: -12,
    focalCity: "Nouakchott",
  },
  {
    code: "MU",
    name: "Mauritius",
    region: "Africa / Eastern Africa",
    latitude: -20.283_333_33,
    longitude: 57.55,
    focalCity: "Port Louis",
  },
  {
    code: "YT",
    name: "Mayotte",
    region: "Africa / Eastern Africa",
    latitude: -12.833_333_33,
    longitude: 45.166_666_66,
    focalCity: "Mamoudzou",
  },
  {
    code: "MX",
    name: "Mexico",
    region: "Americas / North America",
    latitude: 23,
    longitude: -102,
    focalCity: "Mexico City",
  },
  {
    code: "FM",
    name: "Micronesia",
    region: "Oceania / Micronesia",
    latitude: 6.916_666_66,
    longitude: 158.25,
    focalCity: "Palikir",
  },
  {
    code: "MD",
    name: "Moldova",
    region: "Europe / Eastern Europe",
    latitude: 47,
    longitude: 29,
    focalCity: "Chișinău",
  },
  {
    code: "MC",
    name: "Monaco",
    region: "Europe / Western Europe",
    latitude: 43.733_333_33,
    longitude: 7.4,
    focalCity: "Monaco",
  },
  {
    code: "MN",
    name: "Mongolia",
    region: "Asia / Eastern Asia",
    latitude: 46,
    longitude: 105,
    focalCity: "Ulan Bator",
  },
  {
    code: "ME",
    name: "Montenegro",
    region: "Europe / Southeast Europe",
    latitude: 42.5,
    longitude: 19.3,
    focalCity: "Podgorica",
  },
  {
    code: "MS",
    name: "Montserrat",
    region: "Americas / Caribbean",
    latitude: 16.75,
    longitude: -62.2,
    focalCity: "Plymouth",
  },
  {
    code: "MA",
    name: "Morocco",
    region: "Africa / Northern Africa",
    latitude: 32,
    longitude: -5,
    focalCity: "Rabat",
  },
  {
    code: "MZ",
    name: "Mozambique",
    region: "Africa / Eastern Africa",
    latitude: -18.25,
    longitude: 35,
    focalCity: "Maputo",
  },
  {
    code: "MM",
    name: "Myanmar",
    region: "Asia / South-Eastern Asia",
    latitude: 22,
    longitude: 98,
    focalCity: "Naypyidaw",
  },
  {
    code: "NA",
    name: "Namibia",
    region: "Africa / Southern Africa",
    latitude: -22,
    longitude: 17,
    focalCity: "Windhoek",
  },
  {
    code: "NR",
    name: "Nauru",
    region: "Oceania / Micronesia",
    latitude: -0.533_333_33,
    longitude: 166.916_666_66,
    focalCity: "Yaren",
  },
  {
    code: "NP",
    name: "Nepal",
    region: "Asia / Southern Asia",
    latitude: 28,
    longitude: 84,
    focalCity: "Kathmandu",
  },
  {
    code: "NL",
    name: "Netherlands",
    region: "Europe / Western Europe",
    latitude: 52.5,
    longitude: 5.75,
    focalCity: "Amsterdam",
  },
  {
    code: "NC",
    name: "New Caledonia",
    region: "Oceania / Melanesia",
    latitude: -21.5,
    longitude: 165.5,
    focalCity: "Nouméa",
  },
  {
    code: "NZ",
    name: "New Zealand",
    region: "Oceania / Australia and New Zealand",
    latitude: -41,
    longitude: 174,
    focalCity: "Wellington",
  },
  {
    code: "NI",
    name: "Nicaragua",
    region: "Americas / Central America",
    latitude: 13,
    longitude: -85,
    focalCity: "Managua",
  },
  {
    code: "NE",
    name: "Niger",
    region: "Africa / Western Africa",
    latitude: 16,
    longitude: 8,
    focalCity: "Niamey",
  },
  {
    code: "NG",
    name: "Nigeria",
    region: "Africa / Western Africa",
    latitude: 10,
    longitude: 8,
    focalCity: "Abuja",
  },
  {
    code: "NU",
    name: "Niue",
    region: "Oceania / Polynesia",
    latitude: -19.033_333_33,
    longitude: -169.866_666_66,
    focalCity: "Alofi",
  },
  {
    code: "NF",
    name: "Norfolk Island",
    region: "Oceania / Australia and New Zealand",
    latitude: -29.033_333_33,
    longitude: 167.95,
    focalCity: "Kingston",
  },
  {
    code: "KP",
    name: "North Korea",
    region: "Asia / Eastern Asia",
    latitude: 40,
    longitude: 127,
    focalCity: "Pyongyang",
  },
  {
    code: "MK",
    name: "North Macedonia",
    region: "Europe / Southeast Europe",
    latitude: 41.833_333_33,
    longitude: 22,
    focalCity: "Skopje",
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    region: "Oceania / Micronesia",
    latitude: 15.2,
    longitude: 145.75,
    focalCity: "Saipan",
  },
  {
    code: "NO",
    name: "Norway",
    region: "Europe / Northern Europe",
    latitude: 62,
    longitude: 10,
    focalCity: "Oslo",
  },
  {
    code: "OM",
    name: "Oman",
    region: "Asia / Western Asia",
    latitude: 21,
    longitude: 57,
    focalCity: "Muscat",
  },
  {
    code: "PK",
    name: "Pakistan",
    region: "Asia / Southern Asia",
    latitude: 30,
    longitude: 70,
    focalCity: "Islamabad",
  },
  {
    code: "PW",
    name: "Palau",
    region: "Oceania / Micronesia",
    latitude: 7.5,
    longitude: 134.5,
    focalCity: "Ngerulmud",
  },
  {
    code: "PS",
    name: "Palestine",
    region: "Asia / Western Asia",
    latitude: 31.9,
    longitude: 35.2,
    focalCity: "Ramallah",
  },
  {
    code: "PA",
    name: "Panama",
    region: "Americas / Central America",
    latitude: 9,
    longitude: -80,
    focalCity: "Panama City",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    region: "Oceania / Melanesia",
    latitude: -6,
    longitude: 147,
    focalCity: "Port Moresby",
  },
  {
    code: "PY",
    name: "Paraguay",
    region: "Americas / South America",
    latitude: -23,
    longitude: -58,
    focalCity: "Asunción",
  },
  {
    code: "PE",
    name: "Peru",
    region: "Americas / South America",
    latitude: -10,
    longitude: -76,
    focalCity: "Lima",
  },
  {
    code: "PH",
    name: "Philippines",
    region: "Asia / South-Eastern Asia",
    latitude: 13,
    longitude: 122,
    focalCity: "Manila",
  },
  {
    code: "PN",
    name: "Pitcairn Islands",
    region: "Oceania / Polynesia",
    latitude: -25.066_666_66,
    longitude: -130.1,
    focalCity: "Adamstown",
  },
  {
    code: "PL",
    name: "Poland",
    region: "Europe / Central Europe",
    latitude: 52,
    longitude: 20,
    focalCity: "Warsaw",
  },
  {
    code: "PT",
    name: "Portugal",
    region: "Europe / Southern Europe",
    latitude: 39.5,
    longitude: -8,
    focalCity: "Lisbon",
  },
  {
    code: "PR",
    name: "Puerto Rico",
    region: "Americas / Caribbean",
    latitude: 18.25,
    longitude: -66.5,
    focalCity: "San Juan",
  },
  {
    code: "QA",
    name: "Qatar",
    region: "Asia / Western Asia",
    latitude: 25.5,
    longitude: 51.25,
    focalCity: "Doha",
  },
  {
    code: "RE",
    name: "Réunion",
    region: "Africa / Eastern Africa",
    latitude: -21.15,
    longitude: 55.5,
    focalCity: "Saint-Denis",
  },
  {
    code: "RO",
    name: "Romania",
    region: "Europe / Southeast Europe",
    latitude: 46,
    longitude: 25,
    focalCity: "Bucharest",
  },
  {
    code: "RU",
    name: "Russia",
    region: "Europe / Eastern Europe",
    latitude: 60,
    longitude: 100,
    focalCity: "Moscow",
  },
  {
    code: "RW",
    name: "Rwanda",
    region: "Africa / Eastern Africa",
    latitude: -2,
    longitude: 30,
    focalCity: "Kigali",
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    region: "Americas / Caribbean",
    latitude: 18.5,
    longitude: -63.416_666_66,
    focalCity: "Gustavia",
  },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    region: "Africa / Western Africa",
    latitude: -15.95,
    longitude: -5.72,
    focalCity: "Jamestown",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    region: "Americas / Caribbean",
    latitude: 17.333_333_33,
    longitude: -62.75,
    focalCity: "Basseterre",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    region: "Americas / Caribbean",
    latitude: 13.883_333_33,
    longitude: -60.966_666_66,
    focalCity: "Castries",
  },
  {
    code: "MF",
    name: "Saint Martin",
    region: "Americas / Caribbean",
    latitude: 18.083_333_33,
    longitude: -63.95,
    focalCity: "Marigot",
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    region: "Americas / North America",
    latitude: 46.833_333_33,
    longitude: -56.333_333_33,
    focalCity: "Saint-Pierre",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    region: "Americas / Caribbean",
    latitude: 13.25,
    longitude: -61.2,
    focalCity: "Kingstown",
  },
  {
    code: "WS",
    name: "Samoa",
    region: "Oceania / Polynesia",
    latitude: -13.583_333_33,
    longitude: -172.333_333_33,
    focalCity: "Apia",
  },
  {
    code: "SM",
    name: "San Marino",
    region: "Europe / Southern Europe",
    latitude: 43.766_666_66,
    longitude: 12.416_666_66,
    focalCity: "City of San Marino",
  },
  {
    code: "ST",
    name: "São Tomé and Príncipe",
    region: "Africa / Middle Africa",
    latitude: 1,
    longitude: 7,
    focalCity: "São Tomé",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    region: "Asia / Western Asia",
    latitude: 25,
    longitude: 45,
    focalCity: "Riyadh",
  },
  {
    code: "SN",
    name: "Senegal",
    region: "Africa / Western Africa",
    latitude: 14,
    longitude: -14,
    focalCity: "Dakar",
  },
  {
    code: "RS",
    name: "Serbia",
    region: "Europe / Southeast Europe",
    latitude: 44,
    longitude: 21,
    focalCity: "Belgrade",
  },
  {
    code: "SC",
    name: "Seychelles",
    region: "Africa / Eastern Africa",
    latitude: -4.583_333_33,
    longitude: 55.666_666_66,
    focalCity: "Victoria",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    region: "Africa / Western Africa",
    latitude: 8.5,
    longitude: -11.5,
    focalCity: "Freetown",
  },
  {
    code: "SG",
    name: "Singapore",
    region: "Asia / South-Eastern Asia",
    latitude: 1.366_666_66,
    longitude: 103.8,
    focalCity: "Singapore",
  },
  {
    code: "SX",
    name: "Sint Maarten",
    region: "Americas / Caribbean",
    latitude: 18.033_333,
    longitude: -63.05,
    focalCity: "Philipsburg",
  },
  {
    code: "SK",
    name: "Slovakia",
    region: "Europe / Central Europe",
    latitude: 48.666_666_66,
    longitude: 19.5,
    focalCity: "Bratislava",
  },
  {
    code: "SI",
    name: "Slovenia",
    region: "Europe / Central Europe",
    latitude: 46.116_666_66,
    longitude: 14.816_666_66,
    focalCity: "Ljubljana",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    region: "Oceania / Melanesia",
    latitude: -8,
    longitude: 159,
    focalCity: "Honiara",
  },
  {
    code: "SO",
    name: "Somalia",
    region: "Africa / Eastern Africa",
    latitude: 10,
    longitude: 49,
    focalCity: "Mogadishu",
  },
  {
    code: "ZA",
    name: "South Africa",
    region: "Africa / Southern Africa",
    latitude: -29,
    longitude: 24,
    focalCity: "Pretoria",
  },
  {
    code: "GS",
    name: "South Georgia",
    region: "Antarctic",
    latitude: -54.5,
    longitude: -37,
    focalCity: "King Edward Point",
  },
  {
    code: "KR",
    name: "South Korea",
    region: "Asia / Eastern Asia",
    latitude: 37,
    longitude: 127.5,
    focalCity: "Seoul",
  },
  {
    code: "SS",
    name: "South Sudan",
    region: "Africa / Middle Africa",
    latitude: 7,
    longitude: 30,
    focalCity: "Juba",
  },
  {
    code: "ES",
    name: "Spain",
    region: "Europe / Southern Europe",
    latitude: 40,
    longitude: -4,
    focalCity: "Madrid",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    region: "Asia / Southern Asia",
    latitude: 7,
    longitude: 81,
    focalCity: "Colombo",
  },
  {
    code: "SD",
    name: "Sudan",
    region: "Africa / Northern Africa",
    latitude: 15,
    longitude: 30,
    focalCity: "Khartoum",
  },
  {
    code: "SR",
    name: "Suriname",
    region: "Americas / South America",
    latitude: 4,
    longitude: -56,
    focalCity: "Paramaribo",
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    region: "Europe / Northern Europe",
    latitude: 78,
    longitude: 20,
    focalCity: "Longyearbyen",
  },
  {
    code: "SE",
    name: "Sweden",
    region: "Europe / Northern Europe",
    latitude: 62,
    longitude: 15,
    focalCity: "Stockholm",
  },
  {
    code: "CH",
    name: "Switzerland",
    region: "Europe / Western Europe",
    latitude: 47,
    longitude: 8,
    focalCity: "Bern",
  },
  {
    code: "SY",
    name: "Syria",
    region: "Asia / Western Asia",
    latitude: 35,
    longitude: 38,
    focalCity: "Damascus",
  },
  {
    code: "TW",
    name: "Taiwan",
    region: "Asia / Eastern Asia",
    latitude: 23.5,
    longitude: 121,
    focalCity: "Taipei",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    region: "Asia / Central Asia",
    latitude: 39,
    longitude: 71,
    focalCity: "Dushanbe",
  },
  {
    code: "TZ",
    name: "Tanzania",
    region: "Africa / Eastern Africa",
    latitude: -6,
    longitude: 35,
    focalCity: "Dodoma",
  },
  {
    code: "TH",
    name: "Thailand",
    region: "Asia / South-Eastern Asia",
    latitude: 15,
    longitude: 100,
    focalCity: "Bangkok",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    region: "Asia / South-Eastern Asia",
    latitude: -8.833_333_33,
    longitude: 125.916_666_66,
    focalCity: "Dili",
  },
  {
    code: "TG",
    name: "Togo",
    region: "Africa / Western Africa",
    latitude: 8,
    longitude: 1.166_666_66,
    focalCity: "Lomé",
  },
  {
    code: "TK",
    name: "Tokelau",
    region: "Oceania / Polynesia",
    latitude: -9,
    longitude: -172,
    focalCity: "Fakaofo",
  },
  {
    code: "TO",
    name: "Tonga",
    region: "Oceania / Polynesia",
    latitude: -20,
    longitude: -175,
    focalCity: "Nuku\u0027alofa",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    region: "Americas / Caribbean",
    latitude: 11,
    longitude: -61,
    focalCity: "Port of Spain",
  },
  {
    code: "TN",
    name: "Tunisia",
    region: "Africa / Northern Africa",
    latitude: 34,
    longitude: 9,
    focalCity: "Tunis",
  },
  {
    code: "TR",
    name: "Türkiye",
    region: "Asia / Western Asia",
    latitude: 39,
    longitude: 35,
    focalCity: "Ankara",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    region: "Asia / Central Asia",
    latitude: 40,
    longitude: 60,
    focalCity: "Ashgabat",
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    region: "Americas / Caribbean",
    latitude: 21.75,
    longitude: -71.583_333_33,
    focalCity: "Cockburn Town",
  },
  {
    code: "TV",
    name: "Tuvalu",
    region: "Oceania / Polynesia",
    latitude: -8,
    longitude: 178,
    focalCity: "Funafuti",
  },
  {
    code: "UG",
    name: "Uganda",
    region: "Africa / Eastern Africa",
    latitude: 1,
    longitude: 32,
    focalCity: "Kampala",
  },
  {
    code: "UA",
    name: "Ukraine",
    region: "Europe / Eastern Europe",
    latitude: 49,
    longitude: 32,
    focalCity: "Kyiv",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    region: "Asia / Western Asia",
    latitude: 24,
    longitude: 54,
    focalCity: "Abu Dhabi",
  },
  {
    code: "GB",
    name: "United Kingdom",
    region: "Europe / Northern Europe",
    latitude: 54,
    longitude: -2,
    focalCity: "London",
  },
  {
    code: "US",
    name: "United States",
    region: "Americas / North America",
    latitude: 38,
    longitude: -97,
    focalCity: "Washington D.C.",
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    region: "Americas / North America",
    latitude: 19.3,
    longitude: 166.633_333,
    focalCity: "United States Minor Outlying Islands",
  },
  {
    code: "VI",
    name: "United States Virgin Islands",
    region: "Americas / Caribbean",
    latitude: 18.35,
    longitude: -64.933_333,
    focalCity: "Charlotte Amalie",
  },
  {
    code: "UY",
    name: "Uruguay",
    region: "Americas / South America",
    latitude: -33,
    longitude: -56,
    focalCity: "Montevideo",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    region: "Asia / Central Asia",
    latitude: 41,
    longitude: 64,
    focalCity: "Tashkent",
  },
  {
    code: "VU",
    name: "Vanuatu",
    region: "Oceania / Melanesia",
    latitude: -16,
    longitude: 167,
    focalCity: "Port Vila",
  },
  {
    code: "VA",
    name: "Vatican City",
    region: "Europe / Southern Europe",
    latitude: 41.9,
    longitude: 12.45,
    focalCity: "Vatican City",
  },
  {
    code: "VE",
    name: "Venezuela",
    region: "Americas / South America",
    latitude: 8,
    longitude: -66,
    focalCity: "Caracas",
  },
  {
    code: "VN",
    name: "Vietnam",
    region: "Asia / South-Eastern Asia",
    latitude: 16.166_666_66,
    longitude: 107.833_333_33,
    focalCity: "Hanoi",
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    region: "Oceania / Polynesia",
    latitude: -13.3,
    longitude: -176.2,
    focalCity: "Mata-Utu",
  },
  {
    code: "EH",
    name: "Western Sahara",
    region: "Africa / Northern Africa",
    latitude: 24.5,
    longitude: -13,
    focalCity: "El Aaiún",
  },
  {
    code: "YE",
    name: "Yemen",
    region: "Asia / Western Asia",
    latitude: 15,
    longitude: 48,
    focalCity: "Sana\u0027a",
  },
  {
    code: "ZM",
    name: "Zambia",
    region: "Africa / Eastern Africa",
    latitude: -15,
    longitude: 30,
    focalCity: "Lusaka",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    region: "Africa / Eastern Africa",
    latitude: -20,
    longitude: 30,
    focalCity: "Harare",
  },
] satisfies CountrySummary[];

allCountries.forEach((country) => countrySummarySchema.parse(country));
